const PASSWORD_HASH="117aa5c540f10f30459f8f21c8b68e1ba3e71bccd3f98ffda7c00237907eef2d";
const letterText=`sayangkuuu selamattt ulangg tahunn, 19 tahunn sudahhh kamuu berjuang dann belajar, banyakk hal sudahhh terjadii, pelan-pelan dari kamuu remaja menuju dewasa, kamuu beradaptasiii, kamuu berkembangg, terimakasihh udah bertahann selamaa inii, terimaa kasihh selalu menjadii pribadii yangg tangguh, baik untuk keluargaa, sahabatt,dann pacarmuu. tidakk hanya ituu, di umurr 18 menujuu 19, kamuu kenal akuu, tanpaa adaa rencanaa sedikitpunn kitaa punn akhirnya dekatt, dan jadiann di harii selasaa tanggal 30 junii 2026, terimaa kasihh sudahh mau jadii pacarkuu, sehatt selaluu yahh sayangg, panjangg umurr, semogaa selaluu diberkahi, berkelimpahann, selaluu di kelilingii kebaikann, orang2 yangg selaluu supportt dengann smn, i lovee uu bbyy🤍💕 –pacarmuu palingg ganteng alexx bhizer`;
async function hash(t){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(t));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function go(n){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));document.getElementById("p"+n).classList.add("active");scrollTo({top:0,behavior:"smooth"})}
async function unlockFirst(){let i=document.getElementById("firstPw"),m=document.getElementById("firstMsg");if(await hash(i.value.trim())===PASSWORD_HASH){document.getElementById("firstLock").classList.add("hidden");document.getElementById("birthdayContent").classList.remove("hidden")}else{m.textContent="passwordnya belum tepat, coba lagi yaa 🌷";i.value="";i.focus()}}
async function unlock(){let i=document.getElementById("pw"),m=document.getElementById("msg");if(await hash(i.value.trim())===PASSWORD_HASH){go(5);typeLetter()}else{m.textContent="passwordnya salahh 🥺💗";i.value="";i.focus()}}
firstPw.addEventListener("keydown",e=>e.key==="Enter"&&unlockFirst());pw.addEventListener("keydown",e=>e.key==="Enter"&&unlock());
const music=document.getElementById("music");function toggleMusic(){music.paused?music.play().catch(()=>{}):music.pause()}
function updateCountdown(){let n=new Date(),t=new Date(n.getFullYear(),9,7);if(n>=t)t=new Date(n.getFullYear()+1,9,7);let d=Math.max(0,t-n),a=Math.floor(d/864e5),h=Math.floor(d/36e5)%24,m=Math.floor(d/6e4)%60,s=Math.floor(d/1e3)%60;count.textContent=[a,h,m,s].map(x=>String(x).padStart(2,"0")).join(" : ");if(d<=0){giftText.textContent="✨ waktunya tiba! hadiah terbuka untukmu 💗";document.querySelector(".gift .box").textContent="🎁✨"}}updateCountdown();setInterval(updateCountdown,1000);
function typeLetter(){let e=document.getElementById("typed");e.textContent="";let w=letterText.split(" "),i=0;function n(){if(i>=w.length)return;e.textContent+=(i?" ":"")+w[i++];setTimeout(n,145)}n()}
const fs=["🌸","🌷","🌼","🌺","🌻","💮","🪻","🌹"],layer=document.querySelector(".flowers");for(let i=0;i<38;i++){let f=document.createElement("span");f.className="flower";f.textContent=fs[i%fs.length];f.style.setProperty("--left",Math.random()*100+"%");f.style.setProperty("--size",.7+Math.random()*1.1+"rem");f.style.setProperty("--dur",7+Math.random()*8+"s");f.style.setProperty("--delay",-Math.random()*14+"s");f.style.setProperty("--drift",-90+Math.random()*180+"px");layer.appendChild(f)}