const PASSWORD="intanaliselamanya";
const lockScreen=document.getElementById("lockScreen"),main=document.getElementById("main"),entryPassword=document.getElementById("entryPassword"),enterBtn=document.getElementById("enterBtn"),entryError=document.getElementById("entryError"),bgMusic=document.getElementById("bgMusic");
const slides=[...document.querySelectorAll(".slide")],dots=[...document.querySelectorAll(".dot")],counter=document.getElementById("slideCounter"),progressBar=document.getElementById("progressBar");let current=0;
const birthdayText="sayangkuuu selamattt ulangg tahunn, 19 tahunn sudahhh kamuu berjuang dann belajar, banyakk hal sudahh terjadii, pelan-pelan dari kamuu remaja menuju dewasa, kamuu beradaptasiii, kamuu berkembangg, terimakasihh udahh bertahann selamaa inii, terimaa kasihh selalu menjadii pribadii yangg tangguh, baik untuk keluargaa, sahabatt,dann pacarmuu. tidakk hanya ituu, di umurr 18 menujuu 19, kamuu kenal akuu, tanpaa adaa rencanaa sedikitpunn kitaa punn akhirnya dekatt, dan jadiann di harii selasaa tanggal 30 junii 2026, terimaa kasihh sudahh mau jadii pacarkuu, sehatt selaluu yahh sayangg, panjangg umurr, semogaa selaluu diberkahi, berkelimpahann, selaluu di kelilingii kebaikann, orang2 yangg selaluu supportt dengann smn, i lovee uu bbyy🤍💕 –pacarmuu palingg ganteng alexx bhizer";
function typeWords(el,text,speed=115){el.textContent="";const w=text.split(" ");let i=0;(function t(){if(i<w.length){el.textContent+=(i?" ":"")+w[i++];setTimeout(t,speed)}})()}
function showSlide(i){current=Math.max(0,Math.min(i,slides.length-1));slides.forEach((s,n)=>s.classList.toggle("active",n===current));dots.forEach((d,n)=>d.classList.toggle("active",n===current));counter.textContent=`0${current+1} / 04`;progressBar.style.width=`${((current+1)/slides.length)*100}%`;if(current===0&&!showSlide.started){showSlide.started=true;setTimeout(()=>typeWords(document.getElementById("birthdayText"),birthdayText),650)}}
function openSite(){if(entryPassword.value.trim()!==PASSWORD){entryError.textContent="passwordnya belum tepattt, sayang 💗";return}entryError.textContent="";lockScreen.classList.add("hidden");main.classList.remove("hidden");showSlide(0);bgMusic.volume=.28;bgMusic.play().catch(()=>{})}
enterBtn.onclick=openSite;entryPassword.onkeydown=e=>{if(e.key==="Enter")openSite()};document.getElementById("toggleEntryPassword").onclick=()=>{entryPassword.type=entryPassword.type==="password"?"text":"password"};document.getElementById("nextBtn").onclick=()=>showSlide(current+1);document.getElementById("prevBtn").onclick=()=>showSlide(current-1);dots.forEach(d=>d.onclick=()=>showSlide(+d.dataset.go));
document.getElementById("letterBtn").onclick=()=>{const i=document.getElementById("letterPassword"),e=document.getElementById("letterError");if(i.value.trim()!==PASSWORD){e.textContent="passwordnya salahh, coba lagi yaa 💕";return}e.textContent="";document.getElementById("letter").classList.remove("hidden");typeWords(document.getElementById("letterText"),"sayangkuuu, selamattt ulangg tahunnn yaaa. 19 tahunn sudahhh kamuu lewatii, dan akuu banggaa bangettt bisaa kenall, dekettt, sampaii jadii orangg yangg bisaa manggill kamuu sayanggg. semogaa di umurr baruuu inii, kamuu selaluu sehattt, panjanggg umurr, dimudahkann semuaa urusannyaa, dikelilingii hal2 baikk, dan tetappp jadii intann yangg akuu sayanggg. terimaa kasihh sudahh bertahann sejauhh inii. i lovee uu bbyy 🤍💕")};showSlide(0);
